### ISSUE TITLE
[docs] Provide example for schedule messages to be consumed in the future

### ISSUE THREAD

**Issue by tobilg** [celrenheit/sandglass#5]
https://github.com/celrenheit/sandglass#motivation states

> The second is the ability to schedule messages to be consumed in the future. This make it suitable for retries.

which would be really interesting for some of my use cases. Could you please elaborate a bit on that, for example how one could produce a message that is, let's say, to be consumed in 1 week from the time being produced?

Or did I eventually misunderstood the concept? Thanks!

**Comment by celrenheit** [comment]
Hi Tobi,

You can produce a message to be consumed in the future by setting a custom offset (sandflake id):
```go
oneweekFromNow := time.Now().Add(7 * 24 * time.Hour)
gen := sandflake.NewFixedTimeGenerator(oneweekFromNow)

msg := &sgproto.Message{
	Offset: gen.Next(),
	Value:  []byte("Hello"),
}

err := client.ProduceMessage(context.Background(), "topic", "partition", msg)
if err != nil {
	return err
}
```
This should do the job.

Note however that - currently - when producing a new message in the future we cannot guarantee the order between this message and new ones that will be produced (in the present) a week from now.

Also, this relies on sandflake ids which means it should be implemented in each languages. This makes it more difficult to be language agnostic. So, I might move away from using sandflake ids and switch to parameters when producing (something like `ConsumeIn: 3 * time.Hour`).

I'll add this to the readme.
Hope this answers your question.
