### ISSUE TITLE
[clients] starter for client contribution

### ISSUE THREAD

**Issue by stern0** [celrenheit/sandglass#8]
This isn't an issue but a proposal to build a Node.js client.

I assume from the readme statements you'd be happy for me to do so. I was wondering if you are planning to set up a git organisation for this but that's not an expectation, only wondering if you would.

I hope to be able to help on the core too but I'll start with this client for now. By the way this project is ranking as the most trending open source Golang project on github and I feel it's a nice project that's why I'd like to contribute.

**Comment by celrenheit** [comment]
Yes of course.
There isn't an organisation at the moment but feel free to make a pull request for the node.js client inside a directory at https://github.com/celrenheit/sandglass-client.
I would be happy to merge it
